### ISSUE TITLE
Problem with key definitions loading file 

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/dclab#156]
Loading file via Shape-Out2 but I guess the right place for the issue is here:

Unhandled exception in Shape-Out version 2.9.1:
Traceback (most recent call last):
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\main.py", line 482, in dropEvent
    self.add_dataslot(paths=pathlist, is_dcor=is_dcor)
  File "shapeout2\gui\widgets\wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "shapeout2\gui\main.py", line 405, in add_dataslot
    slot_id = self.pipeline.add_slot(path=path)
  File "shapeout2\pipeline\core.py", line 196, in add_slot
    slot = Dataslot(path=path)
  File "shapeout2\pipeline\dataslot.py", line 25, in __init__
    cfg = meta_tool.get_rtdc_config(path)
  File "shapeout2\meta_tool.py", line 25, in get_rtdc_config
    with dclab.new_dataset(path) as ds:
  File "dclab\rtdc_dataset\load.py", line 63, in new_dataset
  File "dclab\rtdc_dataset\load.py", line 22, in load_file
  File "dclab\rtdc_dataset\fmt_hdf5.py", line 228, in __init__
  File "dclab\rtdc_dataset\fmt_hdf5.py", line 293, in parse_config
  File "dclab\rtdc_dataset\config.py", line 55, in __setitem__
  File "dclab\rtdc_dataset\config.py", line 328, in verify_section_key
  File "dclab\definitions\meta_logic.py", line 16, in config_key_exists
ValueError: not enough values to unpack (expected 2, got 1)

I will send you a file example that causes this problem. It is a file that was created with a development version of ShapeIn and older files seem not affected as I can see. However, the key structure between the two remained identical.

I assume it has something to do with the presence of online_filter keys that end on "soft limit" but do not have two features named as in the "polygon point" case. However, I do not understand why older files with the same filters active seem unaffected.

**Comment by paulmueller** [comment]
I believe that's because "pos_x soft limit" is not anticipated. There is a fixed list of valid features in dclab. This should be changed:
https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/definitions/meta_const.py#L118-L149

**Comment by chrherold** [comment]
In this case almost all available features should also be accepted.

Alternatively I can make a list of all that is currently available in Shape-In.

**Comment by paulmueller** [comment]
No thanks, I will just make this more general.
