### ISSUE TITLE
command line interface: tdms2rtdc

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#36]
- [x] option to compute all possible ancillary columns
- [x] batch conversion with source and destination folder

**Comment by paulmueller** [comment]
@phidahl 

The command line interface is documented at https://dclab.readthedocs.io/en/latest/sec_cli.html.

To test it, you need to install dclab from GitHub:

``pip install git+git://github.com/ZELLMECHANIK-DRESDEN/dclab.git``

Please create a new issue if you would like to have anything changed or added.

**Comment by phidahl** [comment]
Hi Paul,

I installed dclab with pip.. But I cannot execute it. I don’t know what package is missing.

I get:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/dclab-tdms2rtdc", line 11, in <module>
    load_entry_point('dclab==0.3.2.dev4', 'console_scripts', 'dclab-tdms2rtdc')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cli

**Comment by paulmueller** [comment]
The submodule "cli.py" is not found. Please try the following:

1. upgrade pip ``pip install --upgrade pip``
2. if you had dclab installed before, uninstall dclab using pip completely (try running ``pip uninstall dclab`` multiple times) and install again from github
3. what files are located in the dclab package directory (you can find out the location by  importing dclab and printing ``dclab.__file__``)
4. does the command work if you add ``from . import cli`` in ``dclab/__init__.py``?

**Comment by paulmueller** [comment]
You have to install the development version ``pip install git+git://github.com/ZELLMECHANIK-DRESDEN/dclab.git`` if you want to use ``tdms2rtdc``.
