### ISSUE TITLE
Error when building .exe with pyinstaller

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/dclab#54]
Sorry that it took me so long to write this issue.

When I wanted to build an executable with pyinstaller of a script containing a dclab import, the build failed with the following error message:

`Traceback (most recent call last):`
`  File "Tracking_MMM.py", line 9, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\dclab\__init__.py", line 15, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\dclab\rtdc_dataset\__init__.py", line 6, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\dclab\rtdc_dataset\core.py", line 14, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\dclab\kde_methods.py", line 11, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\statsmodels\__init__.py", line 8, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\statsmodels\tools\__init__.py", line 1, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\statsmodels\tools\tools.py", line 9, in <module>`
`  File "Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module`
`  File "site-packages\pandas\__init__.py", line 35, in <module>`
`ImportError: C extension: No module named np_datetime not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.` 
`[13560] Failed to execute script Tracking_MMM`

I use conda 4.5.10 with python 2.7.14 on windows 10 and pyinstaller 3.1.1.

**Comment by paulmueller** [comment]
Please try again with PyInstaller 3.4 (release 20 days ago); there appears to have been several fixes for the  pandas library.

**Comment by felix-r** [comment]
PyInstaller 3.4 doesn't seem to work at all on my system. I'm actually using version 3.3.1 of pyinstaller. It's wrong in my first message.

**Comment by paulmueller** [comment]
I have just recently successfully built ShapeOut on Windows 10 using PyInstaller 3.4. Please let me know if this is still an issue.

**Comment by felix-r** [comment]
Sorry that it took me soo long to look into this again. I could now successfully build a very simple file including dclab with pyinstaller 3.3.1 . Sorry pyinstaller 3.4 does currently not work on my machine, no matter what environment I use or what I want to build. 

I think you can close this issue.
